//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoHEmotionPilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emotion
    {
        public int Emo_ID { get; set; }
        public string Emo_Title { get; set; }
        public string Emo_Score { get; set; }
    }
}
