//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AffdexMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class myView
    {
        public string Emp_Name { get; set; }
        public Nullable<int> Number_of_Visits { get; set; }
    }
}
