//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AffdexMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visit()
        {
            this.Shots = new HashSet<Shot>();
        }
    
        public int Visit_ID { get; set; }
        public System.DateTime Visit_Date { get; set; }
        public System.DateTime Visit_Time { get; set; }
        public System.Guid User_ID { get; set; }
        public int Emp_ID { get; set; }
        public string Visit_Reason { get; set; }
        public string Emotion_Summary { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shot> Shots { get; set; }
    }
}
